version: "3.7"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: "booklibdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
volumes:
  postgres_data:
