services:
  api:
    container_name: booklib-api
    build: .
    ports:
      - "5000:80"
    volumes:
      - ".:/app"
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    container_name: booklib-db
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: "booklibdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
volumes:
  postgres_data:
