version: "3.8"

services:
  # PostgreSQL Database service
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bookapi_user
      POSTGRES_PASSWORD: bookapi_pass
      POSTGRES_DB: booklib_db
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookapi_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Booklib API service
  booklib-api:
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
