"""empty message

Revision ID: 3971f6f4550d
Revises: 7fdcfffcbd7d
Create Date: 2024-07-02 12:54:11.990021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3971f6f4550d'
down_revision = '7fdcfffcbd7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
