"""empty message

Revision ID: 612552a941b7
Revises: f212d76693eb
Create Date: 2024-07-03 13:54:46.621250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612552a941b7'
down_revision = 'f212d76693eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('bio')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
