"""Remove genres column from Book

Revision ID: c5d9074922af
Revises: 1338ca05e8d7
Create Date: 2025-09-23 16:53:57.577426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d9074922af'
down_revision = '1338ca05e8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
